
##
# extract WWAN3 IP address from file generated by chat
with open('wwan3ip_Address.txt','r') as ipFile:
    strin=ipFile.read().replace('\n','')

# print strin

strinOP= strin.split('"')
print strinOP[3]

fileIp = open('wwan3Ip.txt','w')
fileIp.write(strinOP[3])
fileIp.close()

##
# extract WWAN3 DNS IP address from file generated by chat
with open('wwan3dnsAddress.txt','r') as ipFile:
    strin=ipFile.read().replace('\n','')


strinOP= strin.split('"')
## DNS IP 1
print strinOP[3]
## DNS IP 2
print strinOP[5]

## save the two IP addresses ready for the dhcpcd command
fileIp = open('wwan3DnsIp.txt','w')
fileIp.write(strinOP[3])
fileIp.write(' ')
fileIp.write(strinOP[5])
fileIp.close()



